# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'AtheerChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AtheerChat
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
